#!/usr/bin/env python3
import re
from typing import Generator, Iterable, NamedTuple

from bs4 import BeautifulSoup
import requests
import os


class RelatorTerm(NamedTuple):
    code: str
    title: str
    description: str


def get_soup() -> BeautifulSoup:
    file_name = "relaterm.html"
    url = "https://www.loc.gov/marc/relators/relaterm.html"

    if os.path.isfile(file_name):
        print(f"Already downloaded {url} as {file_name}.")
    else:
        print(f"Downloading {url} as {file_name} …")
        page = requests.get(url)
        with open(file_name, 'wb') as f:
            f.write(page.content)

    print("Parsing …")
    with open(file_name, 'r') as f:
        soup = BeautifulSoup(f, 'html.parser')

    return soup


def get_terms(soup: BeautifulSoup) -> Generator[RelatorTerm, None, None]:
    # The last definition list on the page is the one we want.
    definition_list = soup.find_all('dl')[-1]
    for term_soup in definition_list.find_all('dt'):
        try:
            yield RelatorTerm(
                code=term_soup.find(class_='relator-code').text.strip(" []"),
                title=term_soup.find(class_='authorized').text.strip(),
                description=term_soup.find_next_sibling('dd').text.strip(),
            )
        except AttributeError:
            # Just skip the invalid ones.
            pass


def writePhpClass(terms: Iterable[RelatorTerm]) -> str:
    constants = []
    descriptions = []

    non_az = re.compile(r"[^A-Z]+")
    whitespace = re.compile(r"\s+")

    for t in terms:
        const_name = non_az.sub('_', t.title.upper()).strip('_')
        constants.append(f"  const {const_name} = '{t.code}';")
        description = whitespace.sub(' ', t.description.translate(str.maketrans({
            r"'": r"\'",
        })))
        descriptions.append(f"    self::{const_name} => '{description}',")

    constants = "\n".join(constants)
    descriptions = "\n".join(descriptions)
    file_name = os.path.basename(__file__)

    return rf"""<?php

namespace RudolfByker\PhpMarcCsl;

/**
 * Class RelatorTerm.
 *
 * Valid options for subfield $4 in fields X00.
 * See https://www.loc.gov/marc/bibliographic/bdx00.html
 * and https://www.loc.gov/marc/relators/relaterm.html .
 *
 * This file is auto-generated by '{file_name}'.
 * Don't edit it directly.
 */
abstract class RelatorTerm {{

{constants}

  /**
   * Relator term descriptions, keyed by relator term code.
   *
   * @var string[]
   */
  public static $terms = [
{descriptions}
  ];

}}
"""


def main():
    file_name = "../src/RelatorTerm.php"
    with open(file_name, 'w') as f:
        print(f"Writing new PHP code to {file_name}")
        f.write(writePhpClass(get_terms(get_soup())))


if __name__ == '__main__':
    main()
